/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/gyms/{gymId}/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get class schedule for athlete
         * @description Retrieve all classes eligible for the authenticated athlete in a gym. Classes are filtered by gym membership and membership plan visibility. Athletes only.
         */
        get: operations["ClassController_getClassSchedule"];
        put?: never;
        /**
         * Create a new class
         * @description Schedule a new training session. Only gym owners can create classes.
         */
        post: operations["ClassController_createClass"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/classes/{classId}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Book a class
         * @description Reserve a spot in a class or join the waitlist if full. Athletes only.
         */
        post: operations["ClassController_bookClass"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/classes/bookings/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel a booking
         * @description Remove an athlete from a class booking. Only allowed while class is published. Athletes only.
         */
        delete: operations["ClassController_cancelBooking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/classes/{classId}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark class attendance
         * @description Record which athletes attended a class. Coaches only. Can mark attendance while class is in progress or completed.
         */
        post: operations["ClassController_markAttendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/classes/{classId}/programming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add or edit class programming
         * @description Create or update workout content and loggable status for a class. Coaches only. Programming can be edited while class is published or booking closed.
         */
        post: operations["ClassController_addOrEditProgramming"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/classes/{classId}/toggle-loggable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle class loggable status
         * @description Toggle whether athletes can log results for this class. Coaches only.
         */
        post: operations["ClassController_toggleLoggableStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/classes/{classId}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually transition class state
         * @description Move a class to the next state in the lifecycle (published → booking_closed → in_progress → completed → archived). Coaches only. State transitions are unidirectional.
         */
        post: operations["ClassController_manuallyTransitionClassState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/classes/{classId}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update class structure
         * @description Adjust class capacity and/or space during the publish/booking phase. Coaches only. Cannot reduce capacity below current booked athletes.
         */
        patch: operations["ClassController_updateClassStructure"];
        trace?: never;
    };
    "/api/gyms/{gymId}/classes/{classId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log a result for a completed class
         * @description Submit performance data for a completed class. Athletes only. Can only log results for classes where athlete was marked present.
         */
        post: operations["ClassController_logResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/classes/results/{resultId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit a logged result
         * @description Update performance data for a result. Athletes only. Can edit until class is archived.
         */
        patch: operations["ClassController_editResult"];
        trace?: never;
    };
    "/api/gyms/{gymId}/configuration/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a training space
         * @description Define a physical training location in the gym. Gym owners only.
         */
        post: operations["GymConfigurationController_createSpace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/configuration/spaces/{spaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a space
         * @description Remove a training space. Cannot delete spaces with active classes. Gym owners only.
         */
        delete: operations["GymConfigurationController_deleteSpace"];
        options?: never;
        head?: never;
        /**
         * Update a space
         * @description Modify space details. Gym owners only.
         */
        patch: operations["GymConfigurationController_updateSpace"];
        trace?: never;
    };
    "/api/gyms/{gymId}/configuration/class-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Configure class types
         * @description Create, update, or delete class types (e.g., CrossFit, Gymnastics). Gym owners only.
         */
        post: operations["GymConfigurationController_configureClassTypes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/configuration/membership-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a membership plan
         * @description Define a subscription tier with pricing and class access. Gym owners only.
         */
        post: operations["GymConfigurationController_createMembershipPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/configuration/membership-plans/{membershipPlanId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a membership plan
         * @description Modify plan pricing, billing cycle, or class access. Gym owners only.
         */
        patch: operations["GymConfigurationController_updateMembershipPlan"];
        trace?: never;
    };
    "/api/gyms/{gymId}/configuration/membership-plans/{membershipPlanId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a membership plan
         * @description Retire a plan. Existing athletes retain access; new athletes cannot purchase. Gym owners only.
         */
        post: operations["GymConfigurationController_archiveMembershipPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/configuration/membership-plans/{membershipPlanId}/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purchase a membership plan
         * @description Subscribe to a plan to gain class access. Athletes only.
         */
        post: operations["GymConfigurationController_purchaseMembershipPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/configuration/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually add a member
         * @description Enroll an athlete without requiring an invite code. Gym owners only.
         */
        post: operations["GymConfigurationController_manuallyAddMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/configuration/coaches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite a coach
         * @description Send an invitation to a user to become a coach. Gym owners only.
         */
        post: operations["GymConfigurationController_inviteCoach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/configuration/coaches/{coachUserId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change coach status
         * @description Enable or disable a coach. Inactive coaches are hidden from new assignments. Gym owners only.
         */
        patch: operations["GymConfigurationController_changeCoachStatus"];
        trace?: never;
    };
    "/api/me/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get authenticated user bookings
         * @description Retrieve all active bookings for the authenticated athlete. Crosses all gyms (user-scoped endpoint).
         */
        get: operations["UserController_getUserBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a gym
         * @description Register a new gym. The authenticated user becomes the gym owner.
         */
        post: operations["GymController_createGym"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gyms/{gymId}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get gym schedule for owner
         * @description Retrieve all classes in gym schedule for owner management. No membership filtering applied. Gym owners only.
         */
        get: operations["GymScheduleController_getGymScheduleForOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ClassScheduleItemDto: {
            /**
             * @description Unique identifier for the class
             * @example uuid-class-id
             */
            id: string;
            /**
             * @description The type of class (e.g., CrossFit, Gymnastics)
             * @example uuid-class-type-id
             */
            classTypeId: string;
            /**
             * @description Human-readable name of the class type
             * @example CrossFit
             */
            classTypeName: string;
            /**
             * @description Date the class is scheduled, YYYY-MM-DD format
             * @example 2024-06-15
             */
            scheduledDate: string;
            /**
             * @description Time the class starts, HH:mm format
             * @example 07:00
             */
            scheduledTime: string;
            /**
             * @description Full name of the coach leading the class
             * @example John Doe
             */
            coachName: string;
            /**
             * @description Total capacity of the class
             * @example 20
             */
            capacity: number;
            /**
             * @description Number of booked (confirmed) spots
             * @example 12
             */
            bookedCount: number;
            /**
             * @description Current state of the class in its lifecycle
             * @example published
             * @enum {string}
             */
            state: "published" | "booking_closed" | "in_progress" | "completed" | "archived";
        };
        GetClassScheduleResponseDto: {
            /** @description List of classes the athlete is eligible to see and book */
            classes: components["schemas"]["ClassScheduleItemDto"][];
        };
        CreateClassDto: {
            /** @example uuid-class-type-id */
            classTypeId: string;
            /** @example uuid-coach-user-id */
            coachUserId: string;
            /** @example uuid-space-id */
            spaceId: string;
            /**
             * @description ISO date string (YYYY-MM-DD)
             * @example 2024-06-15
             */
            scheduledDate: string;
            /**
             * @description Time in HH:mm format
             * @example 07:00
             */
            scheduledTime: string;
            /** @example 20 */
            capacity?: number;
        };
        CreateClassResponseDto: {
            /** @example uuid-class-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example uuid-class-type-id */
            classTypeId: string;
            /** @example uuid-coach-user-id */
            coachUserId: string;
            /** @example uuid-space-id */
            spaceId: string;
            /**
             * Format: date-time
             * @example 2024-06-15T00:00:00.000Z
             */
            scheduledDate: string;
            /** @example 07:00 */
            scheduledTime: string;
            /** @example 20 */
            capacity: number;
            /**
             * @example published
             * @enum {string}
             */
            state: "published" | "booking_closed" | "in_progress" | "completed" | "archived";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            lastModifiedAt: string;
        };
        BookClassDto: {
            /** @example uuid-class-id */
            classId: string;
            /** @example uuid-gym-id */
            gymId: string;
        };
        BookClassResponseDto: {
            /** @example uuid-booking-id */
            id: string;
            /** @example uuid-class-id */
            classId: string;
            /** @example uuid-user-id */
            userId: string;
            /**
             * @example booked
             * @enum {string}
             */
            status: "booked" | "waitlisted" | "cancelled";
            /** @example 1 */
            bookedPosition: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
            /** @example null */
            cancelledAt: Record<string, never> | null;
        };
        CancelBookingResponseDto: {
            /** @example uuid-booking-id */
            id: string;
            /** @example uuid-class-id */
            classId: string;
            /** @example uuid-user-id */
            userId: string;
            /**
             * @example cancelled
             * @enum {string}
             */
            status: "booked" | "waitlisted" | "cancelled";
            /** @example null */
            bookedPosition: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
            /** @example 2024-06-15T10:00:00.000Z */
            cancelledAt: Record<string, never> | null;
        };
        AttendanceRecordDto: {
            /** @example uuid-athlete-user-id */
            athleteUserId: string;
            /** @example true */
            present: boolean;
            /** @example Arrived late */
            notes?: string;
        };
        MarkAttendanceDto: {
            /** @example uuid-class-id */
            classId: string;
            attendanceRecords: components["schemas"]["AttendanceRecordDto"][];
        };
        AttendanceRecordResponseDto: {
            /** @example uuid-attendance-id */
            id: string;
            /** @example uuid-class-id */
            classId: string;
            /** @example uuid-athlete-user-id */
            userId: string;
            /** @example true */
            present: boolean;
            /**
             * Format: date-time
             * @example 2024-06-15T07:30:00.000Z
             */
            markedAt: string;
            /** @example uuid-coach-user-id */
            markedByUserId: string;
            /** @example Arrived late */
            notes: Record<string, never> | null;
        };
        MarkAttendanceResponseDto: {
            /** @example uuid-class-id */
            classId: string;
            attendanceRecords: components["schemas"]["AttendanceRecordResponseDto"][];
        };
        AddOrEditProgrammingDto: {
            /** @example uuid-class-id */
            classId: string;
            /** @example 5 rounds: 20 box jumps, 15 pull-ups, 10 burpees. For time. */
            content: string;
            /** @example true */
            loggable?: boolean;
        };
        AddOrEditProgrammingResponseDto: {
            /** @example uuid-programming-id */
            id: string;
            /** @example uuid-class-id */
            classId: string;
            /** @example 5 rounds: 20 box jumps, 15 pull-ups, 10 burpees. For time. */
            content: string;
            /** @example uuid-coach-user-id */
            createdByUserId: string;
            /**
             * Format: date-time
             * @example 2024-06-14T18:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-06-14T19:00:00.000Z
             */
            lastModifiedAt: string;
            /** @example uuid-coach-user-id */
            lastModifiedByUserId: Record<string, never> | null;
        };
        ToggleLoggableStatusDto: {
            /** @example uuid-class-id */
            classId: string;
        };
        ToggleLoggableStatusResponseDto: {
            /** @example uuid-class-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example uuid-class-type-id */
            classTypeId: string;
            /** @example uuid-coach-user-id */
            coachUserId: string;
            /** @example uuid-space-id */
            spaceId: string;
            /**
             * Format: date-time
             * @example 2024-06-15T00:00:00.000Z
             */
            scheduledDate: string;
            /** @example 07:00 */
            scheduledTime: string;
            /** @example 20 */
            capacity: number;
            /** @example false */
            loggable: boolean;
            /**
             * @example published
             * @enum {string}
             */
            state: "published" | "booking_closed" | "in_progress" | "completed" | "archived";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            lastModifiedAt: string;
        };
        ManuallyTransitionClassStateDto: {
            /** @example uuid-class-id */
            classId: string;
            /**
             * @example booking_closed
             * @enum {string}
             */
            targetState: "published" | "booking_closed" | "in_progress" | "completed" | "archived";
        };
        ManuallyTransitionClassStateResponseDto: {
            /** @example uuid-class-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example uuid-class-type-id */
            classTypeId: string;
            /** @example uuid-coach-user-id */
            coachUserId: string;
            /** @example uuid-space-id */
            spaceId: string;
            /**
             * Format: date-time
             * @example 2024-06-15T00:00:00.000Z
             */
            scheduledDate: string;
            /** @example 07:00 */
            scheduledTime: string;
            /** @example 20 */
            capacity: number;
            /** @example true */
            loggable: boolean;
            /**
             * @example booking_closed
             * @enum {string}
             */
            state: "published" | "booking_closed" | "in_progress" | "completed" | "archived";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-06-15T06:00:00.000Z
             */
            lastModifiedAt: string;
        };
        UpdateClassStructureDto: {
            /** @example uuid-class-id */
            classId: string;
            /** @example 25 */
            capacity?: number;
            /** @example uuid-space-id */
            spaceId?: string;
        };
        UpdateClassStructureResponseDto: {
            /** @example uuid-class-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example uuid-class-type-id */
            classTypeId: string;
            /** @example uuid-coach-user-id */
            coachUserId: string;
            /** @example uuid-space-id */
            spaceId: string;
            /**
             * Format: date-time
             * @example 2024-06-15T00:00:00.000Z
             */
            scheduledDate: string;
            /** @example 07:00 */
            scheduledTime: string;
            /** @example 25 */
            capacity: number;
            /** @example true */
            loggable: boolean;
            /**
             * @example published
             * @enum {string}
             */
            state: "published" | "booking_closed" | "in_progress" | "completed" | "archived";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-06-14T20:00:00.000Z
             */
            lastModifiedAt: string;
        };
        LogResultDto: {
            /** @example uuid-class-id */
            classId: string;
            /**
             * @example time
             * @enum {string}
             */
            metricType: "time" | "reps" | "weight" | "rounds" | "note";
            /** @example 300 */
            value: string;
            /**
             * @example seconds
             * @enum {string}
             */
            unit: "seconds" | "minutes" | "reps" | "kg" | "lb" | "rounds" | "none";
            /** @example Felt strong today */
            notes?: string;
        };
        LogResultResponseDto: {
            /** @example uuid-result-id */
            id: string;
            /** @example uuid-class-id */
            classId: string;
            /** @example uuid-user-id */
            userId: string;
            /**
             * @example time
             * @enum {string}
             */
            metricType: "time" | "reps" | "weight" | "rounds" | "note";
            /** @example 300 */
            value: string;
            /**
             * @example seconds
             * @enum {string}
             */
            unit: "seconds" | "minutes" | "reps" | "kg" | "lb" | "rounds" | "none";
            /** @example Felt strong today */
            notes: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2024-06-15T09:00:00.000Z
             */
            loggedAt: string;
            /** @example null */
            editedAt: Record<string, never> | null;
        };
        EditResultDto: {
            /** @example uuid-result-id */
            resultId: string;
            /**
             * @example time
             * @enum {string}
             */
            metricType?: "time" | "reps" | "weight" | "rounds" | "note";
            /** @example 280 */
            value?: string;
            /**
             * @example seconds
             * @enum {string}
             */
            unit?: "seconds" | "minutes" | "reps" | "kg" | "lb" | "rounds" | "none";
            /** @example Felt better this time */
            notes?: string;
        };
        EditResultResponseDto: {
            /** @example uuid-result-id */
            id: string;
            /** @example uuid-class-id */
            classId: string;
            /** @example uuid-user-id */
            userId: string;
            /**
             * @example time
             * @enum {string}
             */
            metricType: "time" | "reps" | "weight" | "rounds" | "note";
            /** @example 280 */
            value: string;
            /**
             * @example seconds
             * @enum {string}
             */
            unit: "seconds" | "minutes" | "reps" | "kg" | "lb" | "rounds" | "none";
            /** @example Felt better this time */
            notes: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2024-06-15T09:00:00.000Z
             */
            loggedAt: string;
            /** @example 2024-06-15T10:00:00.000Z */
            editedAt: Record<string, never> | null;
        };
        CreateSpaceDto: {
            /** @example Main Floor */
            name: string;
            /** @example 20 */
            baseCapacity: number;
        };
        CreateSpaceResponseDto: {
            /** @example uuid-space-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example Main Floor */
            name: string;
            /** @example 20 */
            baseCapacity: number;
            /** @example null */
            deletedAt: Record<string, never> | null;
        };
        UpdateSpaceDto: {
            /** @example Rig Room */
            name?: string;
            /** @example 25 */
            baseCapacity?: number;
        };
        UpdateSpaceResponseDto: {
            /** @example uuid-space-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example Rig Room */
            name: string;
            /** @example 25 */
            baseCapacity: number;
            /** @example null */
            deletedAt: Record<string, never> | null;
        };
        DeleteSpaceResponseDto: {
            /** @example uuid-space-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example Main Floor */
            name: string;
            /** @example 20 */
            baseCapacity: number;
            /**
             * Format: date-time
             * @example 2024-06-01T00:00:00.000Z
             */
            deletedAt: string;
        };
        ConfigureClassTypesDto: {
            /**
             * @example create
             * @enum {string}
             */
            operation: "create" | "update" | "delete";
            /**
             * @description Required for update and delete operations
             * @example uuid-class-type-id
             */
            classTypeId?: string;
            /**
             * @description Required for create; optional for update
             * @example CrossFit
             */
            name?: string;
            /** @example true */
            loggable?: boolean;
            /**
             * @example time
             * @enum {string}
             */
            resultMetrics?: "time" | "reps" | "weight" | "rounds" | "none";
        };
        ConfigureClassTypesResponseDto: {
            /** @example uuid-class-type-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example CrossFit */
            name: string;
            /** @example true */
            loggable: boolean;
            /**
             * @example time
             * @enum {string}
             */
            resultMetrics: "time" | "reps" | "weight" | "rounds" | "none";
            /** @example null */
            deletedAt: Record<string, never> | null;
        };
        CreateMembershipPlanDto: {
            /** @example Premium Plan */
            name: string;
            /**
             * @description Price in cents
             * @example 9900
             */
            pricing: number;
            /**
             * @example monthly
             * @enum {string}
             */
            billingCycle: "monthly" | "annual";
            /**
             * @example [
             *       "uuid-class-type-id-1",
             *       "uuid-class-type-id-2"
             *     ]
             */
            classTypes: string[];
        };
        CreateMembershipPlanResponseDto: {
            /** @example uuid-membership-plan-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example Premium Plan */
            name: string;
            /** @example 9900 */
            pricing: number;
            /**
             * @example monthly
             * @enum {string}
             */
            billingCycle: "monthly" | "annual";
            /**
             * @example [
             *       "uuid-class-type-id-1"
             *     ]
             */
            classTypes: string[];
            /**
             * @example active
             * @enum {string}
             */
            status: "active" | "archived";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        UpdateMembershipPlanDto: {
            /** @example Gold Plan */
            name?: string;
            /** @example 12900 */
            pricing?: number;
            /**
             * @example annual
             * @enum {string}
             */
            billingCycle?: "monthly" | "annual";
            /**
             * @example [
             *       "uuid-class-type-id-1"
             *     ]
             */
            classTypes?: string[];
        };
        UpdateMembershipPlanResponseDto: {
            /** @example uuid-membership-plan-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example Gold Plan */
            name: string;
            /** @example 12900 */
            pricing: number;
            /**
             * @example annual
             * @enum {string}
             */
            billingCycle: "monthly" | "annual";
            /**
             * @example [
             *       "uuid-class-type-id-1"
             *     ]
             */
            classTypes: string[];
            /**
             * @example active
             * @enum {string}
             */
            status: "active" | "archived";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        ArchiveMembershipPlanResponseDto: {
            /** @example uuid-membership-plan-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example Premium Plan */
            name: string;
            /** @example 9900 */
            pricing: number;
            /**
             * @example monthly
             * @enum {string}
             */
            billingCycle: "monthly" | "annual";
            /**
             * @example [
             *       "uuid-class-type-id-1"
             *     ]
             */
            classTypes: string[];
            /**
             * @example archived
             * @enum {string}
             */
            status: "active" | "archived";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        PurchaseMembershipPlanDto: {
            /** @example uuid-membership-plan-id */
            membershipPlanId: string;
        };
        PurchaseMembershipPlanResponseDto: {
            /** @example uuid-athlete-membership-plan-id */
            id: string;
            /** @example uuid-gym-membership-id */
            gymMembershipId: string;
            /** @example uuid-membership-plan-id */
            membershipPlanId: string;
            /**
             * @example active
             * @enum {string}
             */
            status: "active" | "expired";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            startedAt: string;
            /** @example 2025-01-01T00:00:00.000Z */
            expiresAt: Record<string, never> | null;
        };
        ManuallyAddMemberDto: {
            /** @example uuid-athlete-user-id */
            athleteUserId: string;
            /** @example uuid-membership-plan-id */
            membershipPlanId?: string;
        };
        ManuallyAddMemberResponseDto: {
            /** @example uuid-gym-membership-id */
            gymMembershipId: string;
            /** @example uuid-athlete-user-id */
            userId: string;
            /** @example uuid-gym-id */
            gymId: string;
            /**
             * @example active
             * @enum {string}
             */
            status: "active" | "inactive";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            joinedAt: string;
            /** @example uuid-athlete-membership-plan-id */
            athleteMembershipPlanId?: string;
        };
        InviteCoachDto: {
            /** @example coach@example.com */
            coachEmail: string;
        };
        InviteCoachResponseDto: {
            /** @example uuid-gym-staff-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example uuid-coach-user-id */
            userId: string;
            /**
             * @example coach
             * @enum {string}
             */
            role: "owner" | "coach";
            /**
             * @example active
             * @enum {string}
             */
            status: "active" | "inactive";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            assignedAt: string;
        };
        ChangeCoachStatusResponseDto: {
            /** @example uuid-gym-staff-id */
            id: string;
            /** @example uuid-gym-id */
            gymId: string;
            /** @example uuid-coach-user-id */
            userId: string;
            /**
             * @example coach
             * @enum {string}
             */
            role: "owner" | "coach";
            /**
             * @example inactive
             * @enum {string}
             */
            status: "active" | "inactive";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            assignedAt: string;
        };
        UserBookingItemDto: {
            /**
             * @description Unique identifier for the booking
             * @example uuid-booking-id
             */
            id: string;
            /**
             * @description The class being booked
             * @example uuid-class-id
             */
            classId: string;
            /**
             * @description Current status of the booking
             * @example booked
             * @enum {string}
             */
            status: "booked" | "waitlisted";
        };
        GetUserBookingsResponseDto: {
            /** @description List of the user's active bookings */
            bookings: components["schemas"]["UserBookingItemDto"][];
        };
        CreateGymDto: {
            /** @example CrossFit Downtown */
            name: string;
            /** @example Rua das Flores 123, São Paulo */
            location: string;
            /** @example A premium CrossFit gym in the city center. */
            description?: string;
        };
        CreateGymResponseDto: {
            /** @example uuid-gym-id */
            id: string;
            /** @example CrossFit Downtown */
            name: string;
            /** @example Rua das Flores 123, São Paulo */
            location: string;
            /** @example A premium CrossFit gym. */
            description: Record<string, never> | null;
            /** @example uuid-owner-user-id */
            ownerId: string;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ClassController_getClassSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Class schedule returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetClassScheduleResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Athlete role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassController_createClass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClassDto"];
            };
        };
        responses: {
            /** @description Class created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateClassResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassController_bookClass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Class ID */
                classId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookClassDto"];
            };
        };
        responses: {
            /** @description Class booked or waitlisted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookClassResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Athlete role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassController_cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Booking ID */
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelBookingResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Athlete role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassController_markAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Class ID */
                classId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkAttendanceDto"];
            };
        };
        responses: {
            /** @description Attendance recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkAttendanceResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Coach role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassController_addOrEditProgramming: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Class ID */
                classId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddOrEditProgrammingDto"];
            };
        };
        responses: {
            /** @description Programming saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddOrEditProgrammingResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Coach role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassController_toggleLoggableStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Class ID */
                classId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleLoggableStatusDto"];
            };
        };
        responses: {
            /** @description Loggable status toggled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleLoggableStatusResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Coach role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassController_manuallyTransitionClassState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Class ID */
                classId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManuallyTransitionClassStateDto"];
            };
        };
        responses: {
            /** @description Class state transitioned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManuallyTransitionClassStateResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Coach role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassController_updateClassStructure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Class ID */
                classId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClassStructureDto"];
            };
        };
        responses: {
            /** @description Class structure updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateClassStructureResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Coach role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassController_logResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Class ID */
                classId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogResultDto"];
            };
        };
        responses: {
            /** @description Result logged */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResultResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Athlete role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassController_editResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Result ID */
                resultId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditResultDto"];
            };
        };
        responses: {
            /** @description Result updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditResultResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Athlete role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymConfigurationController_createSpace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpaceDto"];
            };
        };
        responses: {
            /** @description Space created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSpaceResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymConfigurationController_deleteSpace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Space ID */
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Space deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteSpaceResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymConfigurationController_updateSpace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Space ID */
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSpaceDto"];
            };
        };
        responses: {
            /** @description Space updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateSpaceResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymConfigurationController_configureClassTypes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigureClassTypesDto"];
            };
        };
        responses: {
            /** @description Class type configured */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigureClassTypesResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymConfigurationController_createMembershipPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMembershipPlanDto"];
            };
        };
        responses: {
            /** @description Membership plan created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMembershipPlanResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymConfigurationController_updateMembershipPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Membership Plan ID */
                membershipPlanId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMembershipPlanDto"];
            };
        };
        responses: {
            /** @description Membership plan updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateMembershipPlanResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymConfigurationController_archiveMembershipPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Membership Plan ID */
                membershipPlanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membership plan archived */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveMembershipPlanResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymConfigurationController_purchaseMembershipPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Membership Plan ID */
                membershipPlanId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseMembershipPlanDto"];
            };
        };
        responses: {
            /** @description Membership plan purchased */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseMembershipPlanResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Athlete role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymConfigurationController_manuallyAddMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManuallyAddMemberDto"];
            };
        };
        responses: {
            /** @description Member added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManuallyAddMemberResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymConfigurationController_inviteCoach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCoachDto"];
            };
        };
        responses: {
            /** @description Coach invited */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteCoachResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymConfigurationController_changeCoachStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
                /** @description Coach User ID */
                coachUserId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coach status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeCoachStatusResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getUserBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User bookings returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserBookingsResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Athlete role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymController_createGym: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGymDto"];
            };
        };
        responses: {
            /** @description Gym created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGymResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymScheduleController_getGymScheduleForOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gym ID */
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gym schedule returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetClassScheduleResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
